[workspace]
members = [
    # Crates
    "crates/gateway",
    "crates/broker",
    "crates/service",
    "crates/transporters/core",
    "crates/transporters/local",
    "crates/transporters/nats",
]
